### ISSUE TITLE
Feature request: Respect Changesets `privatePackages` field for ignoring packages 

### ISSUE THREAD

**Issue by Vechro** [mscharley/dependency-changesets-action#233]
In `.changesets/config.json` one can configure
```json
  "privatePackages": {
    "version": false,
    "tag": false
  }
```
or
```json
  "privatePackages": false
```

My understanding is that this essentially treats packages that have `"private": true` in the package.json as if it were in the `ignore` array except it also works for packages that have dependent packages in the same monorepo.
E.g package `foo` cannot be in the `ignore` array if package `bar` depends on `foo`, but package `foo` can have `"private": true` in the package.json.
 So when you run `changeset` it won't list those packages for creating Changesets.

Currently this action doesn't respect that same logic and always adds private packages in the changeset even if you couldn't do this through the Changesets CLI. It would be great if it followed the same rules.

**Comment by mscharley** [comment]
Ignoring private packages based on this configuration would be trivial, we already have the changesets configuration and any modified `package.json` files in a PR. The difficult part would be dealing with transitive dependencies. Currently there's no way for the action to know what packages exist, all it has access to easily is the diff from the PR and the ability to pull the full version of any file it knows about. The changesets configuration is in a fixed location, `<changesets-dir>/config.json` and the relevant `package.json` files are mentioned in the PR diff. 

i.e. if `foo` is labelled private, then it is easy to exclude it. But if `foo` is not labelled private and `bar` is, but `foo` depends on `bar` then updates in foo would still be reported in the changeset using the simple implementation.

**Comment by Vechro** [comment]
I think that's totally fine. I would expect it to only exclude packages that are marked private without trying to resolve dependencies. My use case only involves using these private packages in `devDependencies` so if `foo` declares `bar` as devDependency but `bar` has `"private": true` then I would still want a changeset for `foo` as I intend to publish it but not for `bar`.

**Comment by mscharley** [comment]
I'll take a look at this this week then, this shouldn't be hard to implement at all.
